[colors.bright]
black = "#4c4c4c"
blue = "#b3deef"
cyan = "#73cef4"
green = "#c9d05c"
magenta = "#d3b987"
red = "#f43753"
white = "#feffff"
yellow = "#ffc24b"

[colors.normal]
black = "#282828"
blue = "#b3deef"
cyan = "#73cef4"
green = "#c9d05c"
magenta = "#d3b987"
red = "#f43753"
white = "#eeeeee"
yellow = "#ffc24b"

[colors.primary]
background = "#282828"
foreground = "#eeeeee"

[cursor]
style = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 11.5

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[scrolling]
history = 50000

[window]
opacity = 0.5

[window.padding]
x = 20
y = 20
