[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#666666"
blue = "#aaccbb"
cyan = "#42717b"
green = "#cde077"
magenta = "#e16a98"
red = "#d23d3d"
white = "#ffffff"
yellow = "#ffba63"

[colors.normal]
black = "#222222"
blue = "#66a9b9"
cyan = "#6d878d"
green = "#c1ce42"
magenta = "#b7416e"
red = "#e84f4f"
white = "#cccccc"
yellow = "#fe8e3c"

[colors.primary]
background = "#262626"
foreground = "#FFFFFF"

[cursor]
style = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 11.5

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[scrolling]
history = 50000

[window.padding]
x = 0
y = 0
