env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: xterm-256color

font:
  normal:
    family: UbuntuMono Nerd Font
    style: Regular

  bold:
    family: UbuntuMono Nerd Font
    style: Bold

  italic:
    family: UbuntuMono Nerd Font
    style: Italic

  bold_italic:
    family: UbuntuMono Nerd Font
    style: Bold Italic

  size: 13
colors:
  # Default colors
  primary:
    background: '#262626'
    foreground: '#FFFFFF'

  # Normal colors
  normal:
    black:   '#222222'
    red:     '#e84f4f'
    green:   '#c1ce42'
    yellow:  '#fe8e3c'
    blue:    '#66a9b9'
    magenta: '#b7416e'
    cyan:    '#6d878d'
    white:   '#cccccc'

  # Bright colors
  bright:
    black:   '#666666'
    red:     '#d23d3d'
    green:   '#cde077'
    yellow:  '#ffba63'
    blue:    '#aaccbb'
    magenta: '#e16a98'
    cyan:    '#42717b'
    white:   '#ffffff'

cursor:
  style: Beam

scrolling:
  # maximum number of lines in the scrollback buffer. Specifying '0' will
  # disable scrolling.
  history: 50000

window:
  padding:
    x: 0
    y: 0

draw_bold_text_with_bright_colors: true
